---
title: "Final Regression"
author: "Mikhael Gaster & Luke Frymire"
date: "29/07/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


```{r}
library(tidyverse) # Elegant, clear data manipulation
library(fst) # Save and load data quickly
library(lubridate) # Handle dates
library(kableExtra) # Make nice summary tables
library(fixest) # Estimate models with many fixed effects quickly (feols) and make nice regression taables (etable)
library(modelsummary) # Alternative to fixest::etable, preferred by some
library(stargazer)
```



```{r}
CW = as_tibble(read.csv("C:/Users/mikha/OneDrive/Desktop/Dropbox/MIKHAEL NEW/mikhael school/Grad School/Master's/594/Data/FINAL DATA/BERT/FIXED/County X Week - CONSISTENT TWEETERS.csv"))
CM = as_tibble(read.csv("C:/Users/mikha/OneDrive/Desktop/Dropbox/MIKHAEL NEW/mikhael school/Grad School/Master's/594/Data/FINAL DATA/BERT/FIXED/County X Month - CONSISTENT TWEETERS.csv"))


SW = as_tibble(read.csv("C:/Users/mikha/OneDrive/Desktop/Dropbox/MIKHAEL NEW/mikhael school/Grad School/Master's/594/Data/FINAL DATA/BERT/FIXED/State X Week - CONSISTENT TWEETERS.csv"))
SM = as_tibble(read.csv("C:/Users/mikha/OneDrive/Desktop/Dropbox/MIKHAEL NEW/mikhael school/Grad School/Master's/594/Data/FINAL DATA/BERT/FIXED/State X Month - CONSISTENT TWEETERS.csv"))


# CW = as_tibble(read.csv("C:/Users/mikha/OneDrive/Desktop/Dropbox/MIKHAEL NEW/mikhael school/Grad School/Master's/594/Data/FINAL DATA/NO BERT/County X Week - CONSISTENT TWEETERS.csv"))
# CM = as_tibble(read.csv("C:/Users/mikha/OneDrive/Desktop/Dropbox/MIKHAEL NEW/mikhael school/Grad School/Master's/594/Data/FINAL DATA/NO BERT/County X Month - CONSISTENT TWEETERS.csv"))
# 
# 
# SW = as_tibble(read.csv("C:/Users/mikha/OneDrive/Desktop/Dropbox/MIKHAEL NEW/mikhael school/Grad School/Master's/594/Data/FINAL DATA/NO BERT/State X Week - CONSISTENT TWEETERS.csv"))
# SM = as_tibble(read.csv("C:/Users/mikha/OneDrive/Desktop/Dropbox/MIKHAEL NEW/mikhael school/Grad School/Master's/594/Data/FINAL DATA/NO BERT/State X Month - CONSISTENT TWEETERS.csv"))

```


```{r}
CW$date <- as_date(CW$date)
CM$date <- as_date(CM$date)
SW$date <- as_date(SW$date)
SM$date <- as_date(SM$date)

CW$FIPS <- CW$Usable.FIPS
CM$FIPS <- CM$Usable.FIPS
SM$State <- SM$Usable.STATE
SW$State <- SW$Usable.STATE
```

```{r}
CW = CW %>% 
  group_by(FIPS) %>% 
  mutate(Clipped.log.Daily.Cases.per.100k.lag1 = dplyr::lag(Clipped.log.Daily.Cases.per.100k, n=1, order_by=date, default=NA)) %>% 
  mutate(Clipped.log.Daily.Cases.per.100k.lag2 = dplyr::lag(Clipped.log.Daily.Cases.per.100k, n=2, order_by=date, default=NA)) %>% 
  mutate(Clipped.log.Daily.Cases.per.100k.lag3 = dplyr::lag(Clipped.log.Daily.Cases.per.100k, n=3, order_by=date, default=NA)) %>% 
  mutate(Clipped.log.Daily.Cases.per.100k.lag4 = dplyr::lag(Clipped.log.Daily.Cases.per.100k, n=4, order_by=date, default=NA))
  
# CW = CW %>% 
#   group_by(FIPS) %>% 
#   mutate(Clipped.log.Daily.Cases.per.100k.lag2 = dplyr::lag(Clipped.log.Daily.Cases.per.100k, n=2, order_by=date, default=NA))
# CW = CW %>% 
#   group_by(FIPS) %>% 
#   mutate(Clipped.log.Daily.Cases.per.100k.lag3 = dplyr::lag(Clipped.log.Daily.Cases.per.100k, n=3, order_by=date, default=NA))
# CW = CW %>% 
#   group_by(FIPS) %>% 
#   mutate(Clipped.log.Daily.Cases.per.100k.lag4 = dplyr::lag(Clipped.log.Daily.Cases.per.100k, n=4, order_by=date, default=NA))


SW = SW %>% 
  group_by(State) %>% 
  mutate(Clipped.log.Daily.Cases.per.100k.lag1 = dplyr::lag(Clipped.log.Daily.Cases.per.100k, n=1, order_by=date, default=NA)) %>% 
  mutate(Clipped.log.Daily.Cases.per.100k.lag2 = dplyr::lag(Clipped.log.Daily.Cases.per.100k, n=2, order_by=date, default=NA)) %>% 
  mutate(Clipped.log.Daily.Cases.per.100k.lag3 = dplyr::lag(Clipped.log.Daily.Cases.per.100k, n=3, order_by=date, default=NA)) %>% 
  mutate(Clipped.log.Daily.Cases.per.100k.lag4 = dplyr::lag(Clipped.log.Daily.Cases.per.100k, n=4, order_by=date, default=NA))

# SW = SW %>% 
#   group_by(State) %>% 
#   mutate(Clipped.log.Daily.Cases.per.100k.lag2 = dplyr::lag(Clipped.log.Daily.Cases.per.100k, n=2, order_by=date, default=NA))
# SW = SW %>% 
#   group_by(State) %>% 
#   mutate(Clipped.log.Daily.Cases.per.100k.lag3 = dplyr::lag(Clipped.log.Daily.Cases.per.100k, n=3, order_by=date, default=NA))
# SW = SW %>% 
#   group_by(State) %>% 
#   mutate(Clipped.log.Daily.Cases.per.100k.lag4 = dplyr::lag(Clipped.log.Daily.Cases.per.100k, n=4, order_by=date, default=NA))



CW = CW %>% 
  group_by(FIPS) %>% 
  mutate(Clipped.log.Daily.Deaths.per.100k.lag1 = dplyr::lag(Clipped.log.Daily.Deaths.per.100k, n=1, order_by=date, default=NA)) %>% 
  mutate(Clipped.log.Daily.Deaths.per.100k.lag2 = dplyr::lag(Clipped.log.Daily.Deaths.per.100k, n=2, order_by=date, default=NA)) %>% 
  mutate(Clipped.log.Daily.Deaths.per.100k.lag3 = dplyr::lag(Clipped.log.Daily.Deaths.per.100k, n=3, order_by=date, default=NA)) %>% 
  mutate(Clipped.log.Daily.Deaths.per.100k.lag4 = dplyr::lag(Clipped.log.Daily.Deaths.per.100k, n=4, order_by=date, default=NA))
  
# CW = CW %>% 
#   group_by(FIPS) %>% 
#   mutate(Clipped.log.Daily.Deaths.per.100k.lag2 = dplyr::lag(Clipped.log.Daily.Deaths.per.100k, n=2, order_by=date, default=NA))
# CW = CW %>% 
#   group_by(FIPS) %>% 
#   mutate(Clipped.log.Daily.Deaths.per.100k.lag3 = dplyr::lag(Clipped.log.Daily.Deaths.per.100k, n=3, order_by=date, default=NA))
# CW = CW %>% 
#   group_by(FIPS) %>% 
#   mutate(Clipped.log.Daily.Deaths.per.100k.lag4 = dplyr::lag(Clipped.log.Daily.Deaths.per.100k, n=4, order_by=date, default=NA))


SW = SW %>% 
  group_by(State) %>% 
  mutate(Clipped.log.Daily.Deaths.per.100k.lag1 = dplyr::lag(Clipped.log.Daily.Deaths.per.100k, n=1, order_by=date, default=NA)) %>% 
  mutate(Clipped.log.Daily.Deaths.per.100k.lag2 = dplyr::lag(Clipped.log.Daily.Deaths.per.100k, n=2, order_by=date, default=NA)) %>% 
  mutate(Clipped.log.Daily.Deaths.per.100k.lag3 = dplyr::lag(Clipped.log.Daily.Deaths.per.100k, n=3, order_by=date, default=NA)) %>% 
  mutate(Clipped.log.Daily.Deaths.per.100k.lag4 = dplyr::lag(Clipped.log.Daily.Deaths.per.100k, n=4, order_by=date, default=NA))

# SW = SW %>% 
#   group_by(State) %>% 
#   mutate(Clipped.log.Daily.Deaths.per.100k.lag2 = dplyr::lag(Clipped.log.Daily.Deaths.per.100k, n=2, order_by=date, default=NA))
# SW = SW %>% 
#   group_by(State) %>% 
#   mutate(Clipped.log.Daily.Deaths.per.100k.lag3 = dplyr::lag(Clipped.log.Daily.Deaths.per.100k, n=3, order_by=date, default=NA))
# SW = SW %>% 
#   group_by(State) %>% 
#   mutate(Clipped.log.Daily.Deaths.per.100k.lag4 = dplyr::lag(Clipped.log.Daily.Deaths.per.100k, n=4, order_by=date, default=NA))
```


```{r}
# SPECIFICATION 1 PERMUTATIONS


# NO FE'S - WEEK
spec_1_cases = Diffed.Log.CT.Tweets.Per.Tweet ~ Clipped.log.Daily.Cases.per.100k + Clipped.log.Daily.Cases.per.100k.lag1 + Clipped.log.Daily.Cases.per.100k.lag2 + Clipped.log.Daily.Cases.per.100k.lag3 + Clipped.log.Daily.Cases.per.100k.lag4#| factor(FIPS)

spec_1_deaths = Diffed.Log.CT.Tweets.Per.Tweet ~ Clipped.log.Daily.Deaths.per.100k + Clipped.log.Daily.Deaths.per.100k.lag1#| factor(FIPS)

spec_1_BERT_cases = Diffed.Log.BERT.CT.Tweets.Per.Tweet ~ Clipped.log.Daily.Cases.per.100k + Clipped.log.Daily.Cases.per.100k.lag1 + Clipped.log.Daily.Cases.per.100k.lag2 + Clipped.log.Daily.Cases.per.100k.lag3 + Clipped.log.Daily.Cases.per.100k.lag4#| factor(FIPS)

spec_1_BERT_deaths = Diffed.Log.BERT.CT.Tweets.Per.Tweet ~ Clipped.log.Daily.Deaths.per.100k + Clipped.log.Daily.Deaths.per.100k.lag1#| factor(FIPS)


# FE FIPS - WEEK
spec_1_cases_FE_FIPS = Diffed.Log.CT.Tweets.Per.Tweet ~ Clipped.log.Daily.Cases.per.100k + Clipped.log.Daily.Cases.per.100k.lag1 + Clipped.log.Daily.Cases.per.100k.lag2 + Clipped.log.Daily.Cases.per.100k.lag3 + Clipped.log.Daily.Cases.per.100k.lag4| factor(FIPS)

spec_1_deaths_FE_FIPS = Diffed.Log.CT.Tweets.Per.Tweet ~ Clipped.log.Daily.Deaths.per.100k + Clipped.log.Daily.Deaths.per.100k.lag1| factor(FIPS)

spec_1_BERT_cases_FE_FIPS = Diffed.Log.BERT.CT.Tweets.Per.Tweet ~ Clipped.log.Daily.Cases.per.100k + Clipped.log.Daily.Cases.per.100k.lag1 + Clipped.log.Daily.Cases.per.100k.lag2 + Clipped.log.Daily.Cases.per.100k.lag3 + Clipped.log.Daily.Cases.per.100k.lag4| factor(FIPS)

spec_1_BERT_deaths_FE_FIPS = Diffed.Log.BERT.CT.Tweets.Per.Tweet ~ Clipped.log.Daily.Deaths.per.100k + Clipped.log.Daily.Deaths.per.100k.lag1| factor(FIPS)


# FE STATE - WEEK
spec_1_cases_FE_State = Diffed.Log.CT.Tweets.Per.Tweet ~ Clipped.log.Daily.Cases.per.100k + Clipped.log.Daily.Cases.per.100k.lag1 + Clipped.log.Daily.Cases.per.100k.lag2 + Clipped.log.Daily.Cases.per.100k.lag3 + Clipped.log.Daily.Cases.per.100k.lag4| factor(State)

spec_1_deaths_FE_State = Diffed.Log.CT.Tweets.Per.Tweet ~ Clipped.log.Daily.Deaths.per.100k + Clipped.log.Daily.Deaths.per.100k.lag1| factor(State)

spec_1_BERT_cases_FE_State = Diffed.Log.BERT.CT.Tweets.Per.Tweet ~ Clipped.log.Daily.Cases.per.100k + Clipped.log.Daily.Cases.per.100k.lag1 + Clipped.log.Daily.Cases.per.100k.lag2 + Clipped.log.Daily.Cases.per.100k.lag3 + Clipped.log.Daily.Cases.per.100k.lag4| factor(State)

spec_1_BERT_deaths_FE_State = Diffed.Log.BERT.CT.Tweets.Per.Tweet ~ Clipped.log.Daily.Deaths.per.100k + Clipped.log.Daily.Deaths.per.100k.lag1| factor(State)





# NO FE'S - MONTH 
spec_1_cases_month = Diffed.Log.CT.Tweets.Per.Tweet ~ Clipped.log.Daily.Cases.per.100k

spec_1_deaths_month = Diffed.Log.CT.Tweets.Per.Tweet ~ Clipped.log.Daily.Deaths.per.100k

spec_1_BERT_cases_month = Diffed.Log.BERT.CT.Tweets.Per.Tweet ~ Clipped.log.Daily.Cases.per.100k

spec_1_BERT_deaths_month = Diffed.Log.BERT.CT.Tweets.Per.Tweet ~ Clipped.log.Daily.Deaths.per.100k


# FE FIPS - MONTH
spec_1_cases_FE_FIPS_month = Diffed.Log.CT.Tweets.Per.Tweet ~ Clipped.log.Daily.Cases.per.100k

spec_1_deaths_FE_FIPS_month = Diffed.Log.CT.Tweets.Per.Tweet ~ Clipped.log.Daily.Deaths.per.100k | factor(FIPS)

spec_1_BERT_cases_FE_FIPS_month = Diffed.Log.BERT.CT.Tweets.Per.Tweet ~ Clipped.log.Daily.Cases.per.100k | factor(FIPS)

spec_1_BERT_deaths_FE_FIPS_month = Diffed.Log.BERT.CT.Tweets.Per.Tweet ~ Clipped.log.Daily.Deaths.per.100k | factor(FIPS)


# FE STATE - MONTH
spec_1_cases_FE_State_month = Diffed.Log.CT.Tweets.Per.Tweet ~ Clipped.log.Daily.Cases.per.100k | factor(State)

spec_1_deaths_FE_State_month = Diffed.Log.CT.Tweets.Per.Tweet ~ Clipped.log.Daily.Deaths.per.100k | factor(State)

spec_1_BERT_cases_FE_State_month = Diffed.Log.BERT.CT.Tweets.Per.Tweet ~ Clipped.log.Daily.Cases.per.100k | factor(State)

spec_1_BERT_deaths_FE_State_month = Diffed.Log.BERT.CT.Tweets.Per.Tweet ~ Clipped.log.Daily.Deaths.per.100k | factor(State)

```


```{r}
# SPECIFICATION 2 PERMUTATIONS

# NO FE'S - WEEK
spec_2_cases = Diffed.Log.Stopped.COVID.CT.Tweets.After...3.Months ~ Clipped.log.Daily.Cases.per.100k + Clipped.log.Daily.Cases.per.100k.lag1 + Clipped.log.Daily.Cases.per.100k.lag2 + Clipped.log.Daily.Cases.per.100k.lag3 + Clipped.log.Daily.Cases.per.100k.lag4#| factor(FIPS)

spec_2_deaths = Diffed.Log.Stopped.COVID.CT.Tweets.After...3.Months ~ Clipped.log.Daily.Deaths.per.100k + Clipped.log.Daily.Deaths.per.100k.lag1#| factor(FIPS)

spec_2_BERT_cases = Diffed.Log.Stopped.BERT.COVID.CT.Tweets.After...3.Months ~ Clipped.log.Daily.Cases.per.100k + Clipped.log.Daily.Cases.per.100k.lag1 + Clipped.log.Daily.Cases.per.100k.lag2 + Clipped.log.Daily.Cases.per.100k.lag3 + Clipped.log.Daily.Cases.per.100k.lag4#| factor(FIPS)

spec_2_BERT_deaths = Diffed.Log.Stopped.BERT.COVID.CT.Tweets.After...3.Months ~ Clipped.log.Daily.Deaths.per.100k + Clipped.log.Daily.Deaths.per.100k.lag1#| factor(FIPS)


# FE FIPS - WEEK
spec_2_cases_FE_FIPS = Diffed.Log.Stopped.COVID.CT.Tweets.After...3.Months ~ Clipped.log.Daily.Cases.per.100k + Clipped.log.Daily.Cases.per.100k.lag1 + Clipped.log.Daily.Cases.per.100k.lag2 + Clipped.log.Daily.Cases.per.100k.lag3 + Clipped.log.Daily.Cases.per.100k.lag4| factor(FIPS)

spec_2_deaths_FE_FIPS = Diffed.Log.Stopped.COVID.CT.Tweets.After...3.Months ~ Clipped.log.Daily.Deaths.per.100k + Clipped.log.Daily.Deaths.per.100k.lag1| factor(FIPS)

spec_2_BERT_cases_FE_FIPS = Diffed.Log.Stopped.BERT.COVID.CT.Tweets.After...3.Months ~ Clipped.log.Daily.Cases.per.100k + Clipped.log.Daily.Cases.per.100k.lag1 + Clipped.log.Daily.Cases.per.100k.lag2 + Clipped.log.Daily.Cases.per.100k.lag3 + Clipped.log.Daily.Cases.per.100k.lag4| factor(FIPS)

spec_2_BERT_deaths_FE_FIPS = Diffed.Log.Stopped.BERT.COVID.CT.Tweets.After...3.Months ~ Clipped.log.Daily.Deaths.per.100k + Clipped.log.Daily.Deaths.per.100k.lag1| factor(FIPS)


# FE STATE - WEEK
spec_2_cases_FE_State = Diffed.Log.Stopped.COVID.CT.Tweets.After...3.Months ~ Clipped.log.Daily.Cases.per.100k + Clipped.log.Daily.Cases.per.100k.lag1 + Clipped.log.Daily.Cases.per.100k.lag2 + Clipped.log.Daily.Cases.per.100k.lag3 + Clipped.log.Daily.Cases.per.100k.lag4| factor(State)

spec_2_deaths_FE_State = Diffed.Log.Stopped.COVID.CT.Tweets.After...3.Months ~ Clipped.log.Daily.Deaths.per.100k + Clipped.log.Daily.Deaths.per.100k.lag1| factor(State)

spec_2_BERT_cases_FE_State = Diffed.Log.Stopped.BERT.COVID.CT.Tweets.After...3.Months ~ Clipped.log.Daily.Cases.per.100k + Clipped.log.Daily.Cases.per.100k.lag1 + Clipped.log.Daily.Cases.per.100k.lag2 + Clipped.log.Daily.Cases.per.100k.lag3 + Clipped.log.Daily.Cases.per.100k.lag4| factor(State)

spec_2_BERT_deaths_FE_State = Diffed.Log.Stopped.BERT.COVID.CT.Tweets.After...3.Months ~ Clipped.log.Daily.Deaths.per.100k + Clipped.log.Daily.Deaths.per.100k.lag1| factor(State)



# NO FE'S - MONTH
spec_2_cases_month = Diffed.Log.Stopped.COVID.CT.Tweets.After...3.Months ~ Clipped.log.Daily.Cases.per.100k

spec_2_deaths_month = Diffed.Log.Stopped.COVID.CT.Tweets.After...3.Months ~ Clipped.log.Daily.Deaths.per.100k

spec_2_BERT_cases_month = Diffed.Log.Stopped.BERT.COVID.CT.Tweets.After...3.Months ~ Clipped.log.Daily.Cases.per.100k

spec_2_BERT_deaths_month = Diffed.Log.Stopped.BERT.COVID.CT.Tweets.After...3.Months ~ Clipped.log.Daily.Deaths.per.100k


# FE FIPS - MONTH
spec_2_cases_FE_FIPS_month = Diffed.Log.Stopped.COVID.CT.Tweets.After...3.Months ~ Clipped.log.Daily.Cases.per.100k | factor(FIPS)

spec_2_deaths_FE_FIPS_month = Diffed.Log.Stopped.COVID.CT.Tweets.After...3.Months ~ Clipped.log.Daily.Deaths.per.100k | factor(FIPS)

spec_2_BERT_cases_FE_FIPS_month = Diffed.Log.Stopped.BERT.COVID.CT.Tweets.After...3.Months ~ Clipped.log.Daily.Cases.per.100k | factor(FIPS)

spec_2_BERT_deaths_FE_FIPS_month = Diffed.Log.Stopped.BERT.COVID.CT.Tweets.After...3.Months ~ Clipped.log.Daily.Deaths.per.100k | factor(FIPS)


# FE STATE - MONTH
spec_2_cases_FE_State_month = Diffed.Log.Stopped.COVID.CT.Tweets.After...3.Months ~ Clipped.log.Daily.Cases.per.100k | factor(State)

spec_2_deaths_FE_State_month = Diffed.Log.Stopped.COVID.CT.Tweets.After...3.Months ~ Clipped.log.Daily.Deaths.per.100k | factor(State)

spec_2_BERT_cases_FE_State_month = Diffed.Log.Stopped.BERT.COVID.CT.Tweets.After...3.Months ~ Clipped.log.Daily.Cases.per.100k | factor(State)

spec_2_BERT_deaths_FE_State_month = Diffed.Log.Stopped.BERT.COVID.CT.Tweets.After...3.Months ~ Clipped.log.Daily.Deaths.per.100k | factor(State)




```

```{r}
# FILTERING FUNCTIONS

base_county_filter <- function(df) {
  return(df %>%  filter(date >= "2020-03-01" & Sharp.Spike...Cases==0 & Sharp.Spike...Deaths==0))
}

base_state_filter <- function(df) {
  return(df %>%  filter(date >= "2020-03-01" & Missing.Counties.Now==0))
}



```

```{r}
run_spec_1_county <- function(df, filter_fnc, caption_str, time_period){

  save_path_root <- "C:/Users/mikha/OneDrive/Desktop/Dropbox/MIKHAEL NEW/mikhael school/Grad School/Master's/594/Final Analysis - R/TEX Output/"
  if (time_period=="W"){
  a = feols(fml = spec_1_cases, data=filter_fnc(df), se="hetero")
  b = feols(fml = spec_1_cases_FE_FIPS, data=filter_fnc(df))
  c = feols(fml = spec_1_BERT_cases, data=filter_fnc(df), se="hetero")
  d = feols(fml = spec_1_BERT_cases_FE_FIPS, data=filter_fnc(df))
  
  e = feols(fml = spec_1_deaths, data=filter_fnc(df), se="hetero")
  f = feols(fml = spec_1_deaths_FE_FIPS, data=filter_fnc(df))
  g = feols(fml = spec_1_BERT_deaths, data=filter_fnc(df), se="hetero")
  h = feols(fml = spec_1_BERT_deaths_FE_FIPS, data=filter_fnc(df))
  }
  else if (time_period=="M"){
  a = feols(fml = spec_1_cases_month, data=filter_fnc(df), se="hetero")
  b = feols(fml = spec_1_cases_FE_FIPS_month, data=filter_fnc(df))
  c = feols(fml = spec_1_BERT_cases_month, data=filter_fnc(df), se="hetero")
  d = feols(fml = spec_1_BERT_cases_FE_FIPS_month, data=filter_fnc(df))
  
  e = feols(fml = spec_1_deaths_month, data=filter_fnc(df), se="hetero")
  f = feols(fml = spec_1_deaths_FE_FIPS_month, data=filter_fnc(df))
  g = feols(fml = spec_1_BERT_deaths_month, data=filter_fnc(df), se="hetero")
  h = feols(fml = spec_1_BERT_deaths_FE_FIPS_month, data=filter_fnc(df))
  }
  
  etable(a,b,c,d,e,f,g,h, signifCode = c("***"=0.01,"**"=0.05,"*"=0.10), dict=renaming_dict, digits = 5, powerBelow = -7, file=paste(save_path_root, caption_str, ".tex", sep="")) %>%
    kbl(caption = caption_str) %>%
    kable_classic(full_width=F, html_font="Cambria")

  etable(a,b,c,d,e,f,g,h, signifCode = c("***"=0.01,"**"=0.05,"*"=0.10), dict=renaming_dict, digits = 5, powerBelow = -7) %>%
    kbl(caption = caption_str) %>%
    kable_classic(full_width=F, html_font="Cambria")
}
```

```{r}
run_spec_1_state <- function(df, filter_fnc, caption_str, time_period){

  save_path_root <- "C:/Users/mikha/OneDrive/Desktop/Dropbox/MIKHAEL NEW/mikhael school/Grad School/Master's/594/Final Analysis - R/TEX Output/"
  if (time_period=="W"){
  a = feols(fml = spec_1_cases, data=filter_fnc(df), se="hetero")
  b = feols(fml = spec_1_cases_FE_State, data=filter_fnc(df))
  c = feols(fml = spec_1_BERT_cases, data=filter_fnc(df), se="hetero")
  d = feols(fml = spec_1_BERT_cases_FE_State, data=filter_fnc(df))
  
  e = feols(fml = spec_1_deaths, data=filter_fnc(df), se="hetero")
  f = feols(fml = spec_1_deaths_FE_State, data=filter_fnc(df))
  g = feols(fml = spec_1_BERT_deaths, data=filter_fnc(df), se="hetero")
  h = feols(fml = spec_1_BERT_deaths_FE_State, data=filter_fnc(df))
  }
  
  else if (time_period=="M"){
  a = feols(fml = spec_1_cases_month, data=filter_fnc(df), se="hetero")
  b = feols(fml = spec_1_cases_FE_State_month, data=filter_fnc(df))
  c = feols(fml = spec_1_BERT_cases_month, data=filter_fnc(df), se="hetero")
  d = feols(fml = spec_1_BERT_cases_FE_State_month, data=filter_fnc(df))
  
  e = feols(fml = spec_1_deaths_month, data=filter_fnc(df), se="hetero")
  f = feols(fml = spec_1_deaths_FE_State_month, data=filter_fnc(df))
  g = feols(fml = spec_1_BERT_deaths_month, data=filter_fnc(df), se="hetero")
  h = feols(fml = spec_1_BERT_deaths_FE_State_month, data=filter_fnc(df))
  }
  
  etable(a,b,c,d,e,f,g,h, signifCode = c("***"=0.01,"**"=0.05,"*"=0.10), dict=renaming_dict, digits = 5, powerBelow = -7, file=paste(save_path_root, caption_str, ".tex", sep="")) %>%
    kbl(caption = caption_str) %>%
    kable_classic(full_width=F, html_font="Cambria")
  
    etable(a,b,c,d,e,f,g,h, signifCode = c("***"=0.01,"**"=0.05,"*"=0.10), dict=renaming_dict, digits = 5, powerBelow = -7) %>%
    kbl(caption = caption_str) %>%
    kable_classic(full_width=F, html_font="Cambria")
}
```



```{r}
run_spec_1_county(CW, base_county_filter, "Specification 1 - County X Week", "W")
run_spec_1_county(CM, base_county_filter, "Specification 1 - County X Month", "M")
```



```{r}
run_spec_1_state(SW, base_state_filter, "Specification 1 - State X Week", "W")
run_spec_1_state(SM, base_state_filter, "Specification 1 - State X Month", "M")
```


```{r}
glimpse(SM)
```



```{r}
# SM %>% filter(date >= "2020-03-01" & Sharp.Spike...Cases==0 & Sharp.Spike...Deaths==0) %>% filter(Missing.Counties.Now==0)
glimpse(SM)
# base_county_filter(SM)
```




































```{r}
# MAIN SPECIFICATION (unweighted, w/ basic filter)


CW_spec_1_cases = feols(fml = spec_1_cases, data=base_county_filter(CW), se="hetero")
CW_spec_1_deaths = feols(fml = spec_1_deaths, data=base_county_filter(CW), se="hetero")
CW_spec_1_cases_BERT = feols(fml = spec_1_BERT_cases, data=base_county_filter(CW), se="hetero")
CW_spec_1_deaths_BERT = feols(fml = spec_1_BERT_deaths, data=base_county_filter(CW), se="hetero")

CW_spec_1_cases_FE_FIPS = feols(fml = spec_1_cases_FE_FIPS, data=base_county_filter(CW))
CW_spec_1_deaths_FE_FIPS = feols(fml = spec_1_deaths_FE_FIPS, data=base_county_filter(CW))
CW_spec_1_cases_BERT_FE_FIPS = feols(fml = spec_1_BERT_cases_FE_FIPS, data=base_county_filter(CW))
CW_spec_1_deaths_BERT_FE_FIPS = feols(fml = spec_1_BERT_deaths_FE_FIPS, data=base_county_filter(CW))


# stargazer(CW_spec_1_cases, CW_spec_1_deaths, CW_spec_1_cases_BERT, CW_spec_1_deaths_BERT, CW_spec_1_cases_FE_FIPS, CW_spec_1_deaths_FE_FIPS, CW_spec_1_cases_BERT_FE_FIPS, CW_spec_1_deaths_BERT_FE_FIPS, type="html")

models <- list(CW_spec_1_cases, CW_spec_1_cases_BERT, CW_spec_1_cases_FE_FIPS, CW_spec_1_cases_BERT_FE_FIPS, CW_spec_1_deaths, CW_spec_1_deaths_BERT, CW_spec_1_deaths_FE_FIPS,  CW_spec_1_deaths_BERT_FE_FIPS)

# etable(CW_spec_1_cases) %>% 
#   kbl(caption = "test") %>% 
#   kable_classic(full_width=F, html_font="Cambria")
```


```{r}
renaming_dict = c("(Intercept)"="Intercept",
                  "Clipped.log.Daily.Cases.per.100k"="Log cases per 100k", 
                  "Clipped.log.Daily.Cases.per.100k.lag1"="Log cases per 100k (1 wk lag)",
                  "Clipped.log.Daily.Cases.per.100k.lag2"="Log cases per 100k (2 wk lag)",
                  "Clipped.log.Daily.Cases.per.100k.lag3"="Log cases per 100k (3 wk lag)",
                  "Clipped.log.Daily.Cases.per.100k.lag4"="Log cases per 100k (4 wk lag)",
                  
                  "Clipped.log.Daily.Deaths.per.100k"="Log deaths per 100k", 
                  "Clipped.log.Daily.Deaths.per.100k.lag1"="Log deaths per 100k (1 wk lag)",
                  "Clipped.log.Daily.Deaths.per.100k.lag2"="Log deaths per 100k (2 wk lag)",
                  "Clipped.log.Daily.Deaths.per.100k.lag3"="Log deaths per 100k (3 wk lag)",
                  "Clipped.log.Daily.Deaths.per.100k.lag4"="Log deaths per 100k (4 wk lag)",
                  
                  "Diffed.Log.CT.Tweets.Per.Tweet"="Diffed Log CT",
                  "Diffed.Log.BERT.CT.Tweets.Per.Tweet"="Diffed Log BERT CT",
                  
                  "factor(FIPS)"="County",
                  
                  "CW_spec_1_cases"="as ",
                  "CW_spec_1_cases_BERT"="",
                  "CW_spec_1_cases_FE_FIPS"="",
                  "CW_spec_1_cases_BERT_FE_FIPS"="",
                  "CW_spec_1_deaths"="",
                  "CW_spec_1_deaths_BERT"="",
                  "CW_spec_1_deaths_FE_FIPS"="",
                  "CW_spec_1_deaths_BERT_FE_FIPS"=""
                  
                  )
```


```{r}
# etable(models, signifCode = c("***"=0.01,"**"=0.05,"*"=0.10), dict=renaming_dict) %>% 
#   kbl(caption = "Specification 1 - County X Week") %>% 
#   kable_classic(full_width=F, html_font="Cambria")


etable(CW_spec_1_cases, CW_spec_1_cases_FE_FIPS, CW_spec_1_cases_BERT, CW_spec_1_cases_BERT_FE_FIPS, CW_spec_1_deaths, CW_spec_1_deaths_BERT, CW_spec_1_deaths_FE_FIPS,  CW_spec_1_deaths_BERT_FE_FIPS, signifCode = c("***"=0.01,"**"=0.05,"*"=0.10), dict=renaming_dict, digits = 5, powerBelow = -7) %>%
  kbl(caption = "Specification 1 - County X Week") %>%
  kable_classic(full_width=F, html_font="Cambria")

```






```{r}
# filtered_CW <- CW %>%  filter(Num..Users > 50 & Sharp.Spike...Cases==0 & date > "2019-03-01")
filtered_CW <- CW %>%  filter(Sharp.Spike...Cases==0 & date > "2019-03-01")

CW_reg1_cases = feols(fml = spec_1_cases, weights=filtered_CW$Num..Users, data=filtered_CW)
CW_reg1_deaths = feols(fml= spec_1_deaths, weights=filtered_CW$Num..Users, data=filtered_CW)

CW_reg1_BERT_cases = feols(fml = spec_1_BERT_cases, weights = filtered_CW$Num..Users, data=filtered_CW)
CW_reg1_BERT_deaths = feols(fml= spec_1_BERT_deaths, weights = filtered_CW$Num..Users, data=filtered_CW)

# CW_reg1_cases = feols(fml = spec_1_cases, weights=filtered_CW$Num..Users, data=filtered_CW)
# CW_reg1_deaths = feols(fml= spec_1_deaths, weights=filtered_CW$Num..Users, data=filtered_CW)
# 
# CW_reg1_BERT_cases = feols(fml = spec_1_BERT_cases, weights = filtered_CW$Num..Users, data=filtered_CW)
# CW_reg1_BERT_deaths = feols(fml= spec_1_BERT_deaths, weights = filtered_CW$Num..Users, data=filtered_CW)


summary(CW_reg1_cases)
summary(CW_reg1_deaths)
summary(CW_reg1_BERT_cases)
summary(CW_reg1_BERT_deaths)
```






```{r}
# PLOTTING
ggplot(data=SM, aes(x=date))+
  geom_point(aes(y=Diffed.Log.BERT.COVID.CT.Tweets.Per.Tweet), colour="red")+
  geom_point(aes(y=Clipped.log.Daily.Cases.per.100k), colour="black")

```

